name: Deploy
on:
  workflow_dispatch:
  push:
    tags:
      - admin-qa-version
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          echo Hello!
