name: Deploy Admin to Test
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: jaywcjlove/github-action-package@main
        id: info
        with:
           version: ${{ inputs.version }}.0
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add package.json
          git commit -m "chore(admin): bump version to v${{ inputs.version }}.0"
          git push origin main
      - uses: EndBug/latest-tag@latest
        with:
          ref: admin-v${{ inputs.version }}.0
      - uses: EndBug/latest-tag@latest
        with:
          ref: admin-qa-version
      - name: Create deployment branch
        run: |
          git switch --create admin-v${{ inputs.version }}
          git push origin admin-v${{ inputs.version }}
