name: Deploy Admin hotfix to Test
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create patch
        run: |
          npm version patch
          git push origin main
      - uses: EndBug/latest-tag@latest
        with:
          ref: admin-qa-version
