name: Deploy Admin hotfix to Test
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create patch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          npm version patch -m "chore(admin): bump version to %s"
          git push origin $(git rev-parse --abbrev-ref HEAD)
      - name: Get version
        id: version
        run: |
          echo "version=$(jq --raw-output '.version' package.json)" >> $GITHUB_OUTPUT
      - uses: EndBug/latest-tag@latest
        with:
          ref: admin-v${{ steps.version.outputs.version }}
      - uses: EndBug/latest-tag@latest
        with:
          ref: admin-qa-version
